name: CI-CD Workflow
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Run a one-line script
              run: |
                echo We are building the project.
                npm install
                npm run build
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Run a one-line script
              run: |
                echo We are testing the project.
                npm install
                npm test
    deploy:
        needs: [build, test]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Run a one-line script
              run: echo Hello, world! We are deploying the project.